#!/usr/bin/bash

shopt -s extglob


while true
do
    read -p "Do you want to list all tables in this database? (y/n): " choice

    choice=${choice,,}

    case "$choice" in
        "q")
            read -p "Do you want to return to the main list? (y/n): " answer
            answer=${answer,,}

            case "$answer" in
                y)
                    echo "Returning to the main list..."
		. ~/project/mainOptions
                    break
                    ;;
                n)
                    echo "Continue listing tables..."
                    continue
                    ;;
                *)
                    echo "Invalid option"
                    ;;
            esac
            ;;

        "y")
            if [ -z "$(ls -A)" ]
then
                read -p "There are no Tables created in this Database. Press enter to create one." CR
                . ~/project/createTable
            else

                echo "Listing all tables in the connected database:"
                ls | grep -v '_metadata'
                continue
            fi
            ;;

        "n")
            echo "Returning to the main list..."
            . ~/project/mainOptions
            break
            ;;
        *)
            echo "Invalid option"
            ;;
    esac
done

. ~/project/mainOptions 
