#!/bin/bash

shopt -s extglob
export LC_COLLATE=C
all_pkarr=()


while true; do
    read -p "Enter the table name you want to select data from: " tablename

    tablename=${tablename,,}
    
    case "$tablename" in
        "q")
            read -p "Do you want to return to the main list? (y/n): " answer
            answer=${answer,,}

            case "$answer" in
                y)
                    echo "Returning to the main list..."
                    . ~/project/mainEntry 
                    exit
                    ;;
                n)
                    echo "Continue listing a database..."
                    continue
                    ;;
                *)
                    echo "Invalid option"
                    ;;
            esac
            ;;
        *)
            if [ ! -f "$tablename" ]; then
                echo "Please enter a valid table name." 
            else
col_arr=$(awk -F ':' 'NR == 1 {gsub(/:$/, "", $0); print $0}' "${tablename}_metadata")
numofcol=$(awk -F ':' 'END {print NF}' "${tablename}_metadata")
break

            fi
            ;;
    esac
done

PS3="Select an option: "
select option in "Select All" "Select Specific Row" "Select Specific Columns" "Exit"; do
    case $REPLY in
        1)
            echo "NR|${col_arr[@]}"
            awk 'BEGIN{ FS=":" } { print NR "|" substr($0, 1, length($0)-1) }' "$tablename"
            ;;
        2)

echo "All columns"
echo "-------------"
echo "$col_arr" | tr ':' '\n' | awk '{print NR"-"$0; print "-------------"}'
 

while true
do
read -p "please enter number of col you want to select :" colnum
if [[ $colnum =~ ^[0-9]+$ && $numofcol -gt $colnum ]]
then
read -p "please enter value of col you want to select= " valueofcol
echo "Row num |"${col_arr[@]}
awk -v col="$colnum" -v value="$valueofcol" -F ':' '{
if($col ==  value)
print NR"       |" substr($0, 1, length($0)-1)
}' $tablename
break
else 
echo "column not found please enter a valid number!"
continue
fi
done
;;
        3)
          
echo "All columns"
echo "-------------"
echo "$col_arr" | tr ':' '\n' | awk '{print NR"-"$0; print "-------------"}'

      read -p "Please enter the number of the column you want to select: " colnum

if [[ $colnum =~ ^[0-9]+$ && $numofcol -gt $colnum ]]
then
               
           awk -v col="$colnum" -F ':' '{print $col}' "$tablename"
            else 
                echo "Column not found!"
            fi
            ;;
        4)
            
. ~/project/mainOptions
            ;;
        *)
            echo "Invalid option. Please choose a number between 1 and 4."
            ;;
    esac
done
